services:
  frontend:
    container_name: frontend
    build: ./src/frontend/TickerAlertApp/
    ports:
      - ${FRONTEND_PORT}:80
      - 443:443
    depends_on:
      - backend-api
    networks:
      - tickers-network
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${CERTBOT_EMAIL} -d ${CERTBOT_DOMAIN} --agree-tos
    networks:
      - tickers-network

  backend-api:
    container_name: backend-api
    build:
      context: ./src/backend/TickerAlert/
      dockerfile: ./TickerAlert.Api/Dockerfile
    environment:
      - AllowedHosts=*
      - AllowedOrigins__AngularApp=${ANGULAR_APP_ORIGIN}
      - ConnectionStrings__TickerAlertsDatabase=${API_DB_CONNECTION_STRING}
      - Services__Finnhub__BaseUrl=${FINNHUB_BASEURL}
      - Services__Finnhub__ApiKey=${FINNHUB_API_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__Key=${JWT_KEY}
      - ASPNETCORE_URLS=http://*:80
      - EmailService__ApiKey=${EMAIL_SERVICE_API_KEY}
      - EmailService__ApiBaseUrl=${EMAIL_SERVICE_API_BASE_URL}
      - EmailService__SenderEmail=${EMAIL_SERVICE_SENDER_EMAIL}
      - EmailService__SenderName=${EMAIL_SERVICE_SENDER_NAME}
    depends_on:
      - ticker-db
    networks:
      - tickers-network

  ticker-db:
    container_name: ticker-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: TickerAlert
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tickers-network

volumes:
  postgres_data:
    driver: local

networks:
  tickers-network:
    driver: bridge
