version: "3.8"

services:
  frontend:
    container_name: frontend
    build: ./src/frontend/TickerAlertApp/
    ports:
      - 80:80
    depends_on:
      - backend-api

  backend-api:
    container_name: backend-api
    build:
      context: ./src/backend/TickerAlert/
      dockerfile: ./TickerAlert.Api/Dockerfile
    environment:
      - AllowedHosts=*
      - AllowedOrigins__AngularApp=http://frontend:80
      - ConnectionStrings__TickerAlertsDatabase=${API_DB_CONNECTION_STRING}
      - Services__Finnhub__BaseUrl=${FINNHUB_BASEURL}
      - Services__Finnhub__ApiKey=${FINNHUB_API_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__Key=${JWT_KEY}
    ports:
      - 5001:80
    depends_on:
      - ticker-db

  ticker-db:
    container_name: ticker-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: TickerAlert
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
